CREATE VIEW VIEW_USER_INFORMATION AS 
SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, 
CC.CITY_NAME AS CURRENT_CITY, CC.STATE_NAME AS CURRENT_STATE, CC.COUNTRY_NAME AS CURRENT_COUNTRY,
HC.CITY_NAME AS HOMETOWN_CITY, HC.STATE_NAME AS HOMETOWN_STATE, HC.COUNTRY_NAME AS HOMETOWN_COUNTRY,
P.INSTITUTION AS INSTITUTION_NAME, E.PROGRAM_YEAR, P.CONCENTRATION AS PROGRAM_CONCENTRATION, P.DEGREE AS PROGRAM_DEGREE
FROM USERS U
LEFT JOIN USER_CURRENT_CITIES A ON A.USER_ID = U.USER_ID
LEFT JOIN USER_HOMETOWN_CITIES B ON B.USER_ID = U.USER_ID
LEFT JOIN CITIES CC ON CC.CITY_ID = A.CURRENT_CITY_ID
LEFT JOIN CITIES HC ON HC.CITY_ID = B.HOMETOWN_CITY_ID
LEFT JOIN EDUCATION E ON U.USER_ID = E.USER_ID
LEFT JOIN PROGRAMS P ON P.PROGRAM_ID = E.PROGRAM_ID;


CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT * FROM FRIENDS;


CREATE VIEW VIEW_PHOTO_INFORMATION AS 
SELECT  A.ALBUM_ID, A.ALBUM_OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME, A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK, A.ALBUM_VISIBILITY, 
P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
FROM ALBUMS A 
LEFT JOIN PHOTOS P  
ON A.ALBUM_ID = P.ALBUM_ID;

CREATE VIEW VIEW_EVENT_INFORMATION AS 
SELECT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE, E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE,
E.EVENT_SUBTYPE, E.EVENT_ADDRESS, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, E.EVENT_START_TIME, E.EVENT_END_TIME
FROM USER_EVENTS E 
LEFT JOIN CITIES C 
ON E.EVENT_CITY_ID = C.CITY_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y
FROM TAGS;