INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER)
SELECT DISTINCT USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER
FROM project1.Public_User_Information;

INSERT INTO CITIES (CITY_NAME, STATE_NAME, COUNTRY_NAME)
SELECT DISTINCT CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY
FROM project1.Public_User_Information;
UNION
SELECT DISTINCT HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY
FROM project1.Public_User_Information;
UNION
SELECT DISTINCT EVENT_CITY, EVENT_STATE, EVENT_COUNTRY
FROM project1.Public_Event_Information;

INSERT INTO USER_CURRENT_CITIES (USER_ID, CURRENT_CITY_ID)
SELECT DISTINCT P.USER_ID, G.CITY_ID
FROM project1.Public_User_Information P 
INNER JOIN CITIES G
ON ((P.CURRENT_CITY = G.CITY_NAME)
AND (P.CURRENT_COUNTRY = G.COUNTRY_NAME)
AND (P.CURRENT_STATE = G.STATE_NAME));

INSERT INTO USER_HOMETOWN_CITIES (USER_ID, HOMETOWN_CITY_ID)
SELECT DISTINCT P.USER_ID, G.CITY_ID
FROM project1.Public_User_Information P 
INNER JOIN CITIES G
ON ((P.HOMETOWN_CITY = G.CITY_NAME)
AND (P.HOMETOWN_STATE = G.STATE_NAME)
AND (P.HOMETOWN_COUNTRY = G.COUNTRY_NAME));

INSERT INTO FRIENDS
SELECT * FROM project1.Public_Are_Friends;

INSERT INTO USER_EVENTS (EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_ADDRESS, EVENT_CITY_ID, EVENT_START_TIME, EVENT_END_TIME)
SELECT DISTINCT P.EVENT_ID, P.EVENT_CREATOR_ID, P.EVENT_NAME, P.EVENT_TAGLINE, P.EVENT_DESCRIPTION, P.EVENT_HOST, P.EVENT_TYPE, P.EVENT_SUBTYPE, P.EVENT_ADDRESS, G.CITY_ID AS EVENT_CITY_ID, P.EVENT_START_TIME, P.EVENT_END_TIME
FROM project1.Public_Event_Information P
INNER JOIN CITIES G
ON ((P.EVENT_CITY = G.CITY_NAME)
AND (P.EVENT_STATE = G.STATE_NAME)
AND (P.EVENT_COUNTRY = G.COUNTRY_NAME)); 


INSERT INTO PROGRAMS (INSTITUTION, CONCENTRATION, DEGREE)
SELECT DISTINCT INSTITUTION_NAME, PROGRAM_CONCENTRATION, PROGRAM_DEGREE
FROM project1.Public_User_Information
WHERE INSTITUTION_NAME IS NOT NULL AND PROGRAM_CONCENTRATION IS NOT NULL AND PROGRAM_DEGREE IS NOT NULL;


INSERT INTO EDUCATION (USER_ID, PROGRAM_ID, PROGRAM_YEAR)
SELECT DISTINCT P.USER_ID, R.PROGRAM_ID, P.PROGRAM_YEAR
FROM project1.Public_User_Information P, PROGRAMS R
WHERE P.INSTITUTION_NAME = R.INSTITUTION AND P.PROGRAM_CONCENTRATION = R.CONCENTRATION AND P.PROGRAM_DEGREE = R.DEGREE;

SET AUTOCOMMIT OFF;

INSERT INTO ALBUMS (ALBUM_ID, ALBUM_OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY)
SELECT DISTINCT ALBUM_ID, OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY
FROM project1.Public_Photo_Information;

INSERT INTO PHOTOS (PHOTO_ID, ALBUM_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK)
SELECT PHOTO_ID, ALBUM_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK
FROM project1.Public_Photo_Information;

COMMIT;
SET AUTOCOMMIT ON;

INSERT INTO TAGS (TAG_PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X, TAG_Y)
SELECT PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE
FROM project1.Public_Tag_Information;